name: Build and deploy Node.js backend to Azure Web App - xr-messagibg


on:
  push:
    branches:
      - production  # or your branch name
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies from root
        run: npm install  # This installs npm-run-all too

      - name: Build & Start (if needed)
        run: npm run start  # or npm run build/start depending on your scripts

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: xr-messagibg
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B13970A649E545C293BE9252353C16B1 }}
          package: .
